### ISSUE TITLE
In Ruby 3.1 I am getting a gem error

### ISSUE THREAD

**Issue by mikebaldry** [jaynetics/character_set#2]
> You have already activated "set 1.0.3", but your Gemfile requires set 1.0.2. 

`set` is a default gem at 1.0.2 but as `character_set` depends on `sorted_set ~> 1.0`, installing it can update to 1.0.3, and then it causes these issues. Even if you manually add `gem 'set', '= 1.0.2' ; gem 'sorted_set', '= 1.0.2'` it still manages to load 1.0.3 in some cases until you manually uninstall it.

Maybe lock to `1.0.2`?

**Comment by jaynetics** [comment]
hi @mikebaldry and thanks for the report!

the set dependencies have caused various nuisances over time so i've now included their code (which is actually only used as fallback on some exotic Rubies and for testing) directly in the gem.

i've just released v1.7.0 which no longer depends on sorted_set.

btw, out of curiosity, are you using character_set directly or via client_side_validations/js_regex?

**Comment by mikebaldry** [comment]
Great, thanks. I'm using it via `js_regex`
